stages:
  - check
  - package

check-helm:
  stage: check
  script:
    - helm lint ./microservice

package-helm:
  stage: package
  script:
    - helm repo add microservice http://localhost:8080
    - helm plugin install https://github.com/chartmuseum/helm-push
    - helm cm-push ./microservice http://localhost:8080