stages:
  - check
  - spinup
  - package

check-helm:
  stage: check
  script:
    - helm lint ./microservice

spinup-chartmuseum:
  stage: spinup
  script:
    - docker compose up -d

package-helm:
  stage: package
  script:
    - ./helm-push.sh